INSERT INTO PASSPORT ( ID , NUMBER,CREATED_DATE,LAST_UPDATED  ) VALUES ( 350,'IND123',sysdate() ,sysdate());
INSERT INTO PASSPORT ( ID , NUMBER,CREATED_DATE,LAST_UPDATED  ) VALUES ( 351,'IND789',sysdate() ,sysdate() );
INSERT INTO PASSPORT ( ID , NUMBER,CREATED_DATE,LAST_UPDATED  ) VALUES ( 352,'IND987',sysdate() ,sysdate() );


INSERT INTO STUDENT ( ID , NAME,CREATED_DATE,LAST_UPDATED,PASSPORT_ID   ) VALUES ( 300,'madhav',sysdate() ,sysdate(),350);
INSERT INTO STUDENT ( ID , NAME,CREATED_DATE,LAST_UPDATED,PASSPORT_ID  ) VALUES ( 301,'teja',sysdate() ,sysdate(),351 );
INSERT INTO STUDENT ( ID , NAME,CREATED_DATE,LAST_UPDATED,PASSPORT_ID  ) VALUES ( 302,'kumar',sysdate() ,sysdate(),352 );



